apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-nginx
spec:
  type: NodePort
  selector:
    # app=nginx 라벨을 갖는 파드들을 서비스 대상으로 간주함.
    app: nginx
  ports:
    - name: web-port
      # 파드 내부에서 열린 포트번호. 외부에 노출하는 대상.
      targetPort: 80
      # 클러스터 내부에서 clusterIP를 통해 파드에 접근할 때 쓰는 포트번호.
      port: 8080
      # 클러스터 외부에서 노드 IP를 통해 파드에 접근할 때 쓰는 포트번호. (미설정 할 경우 30000 ~ 32767 사이에서 랜덤으로 지정됨.)
      nodePort: 30000
