apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo-hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: echo-hostname
          image: alicek106/rr-test:echo-hostname
          ports:
            - containerPort: 80
