apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: pod-webserver
      labels:
        app: nginx
    spec:
      containers:
        - name: webserver
          image: nginx:latest
          ports:
            - containerPort: 80
