apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    # 볼륨 크기가 최소 4Gi 에 해당하는 PV 와 연결.
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-mount-pod
spec:
  volumes:
    - name: ebs-pv-volume
      persistentVolumeClaim:
        claimName: ebs-pvc
  containers:
    - name: ebs-mount-container
      image: busybox
      args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        # ebs-pv-volume 이라는 PVC를 사용.
        - name: ebs-pv-volume
          mountPath: /mnt
