apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    # 볼륨 크기가 최소 4Gi 에 해당하는 PV 와 연결.
    requests:
      storage: 4Gi
