apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-using-image-registry-secrets
spec:
  replicas: 3
  selector:
    matchLabels:  # matchLabels 에 있는 라벨이 붙은 파드들을 리플리카셋으로 묶음.
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          # image: <프라이빗 레지스트리 주소>:<태그>
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ecr-registry-auth-by-cmd
