apiVersion: v1
kind: Pod
metadata:
  name: value-from-secret
spec:
  volumes:
    # my-password 라는 시크릿을 컨테이너에 마운트하는 데 필요한 볼륨 정의
    - name: secret-volume
      secret:
        # 가져올 시크릿
        secretName: my-password
        # my-password 시크릿에 있는 password 키/값만 선택하고 값은 /etc/secret/password 에 저장함
        items:
          - key: password
            path: /etc/secret/password
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      volumeMounts:
        # secret-volume 이 불러올 시크릿 키/값을 /etc/secret 에 마운트시킨다
        - name: secret-volume
          mountPath: /etc/secret
