apiVersion: v1
kind: Pod
metadata:
  name: value-from-secret
spec:
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      env:
        - name: MY_PW
          valueFrom:
             # my-password 라는 시크릿의 password 키/값을 가져와 MY_PW 라는 이름으로 바꿈.
            secretKeyRef:
              name: my-password
              key: password
