apiVersion: v1
kind: Pod
metadata:
  name: value-from-secret
spec:
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      env:
        - name: MY_PW
          valueFrom:
            secretKeyeRef:
              name: my-password
              key: password
