apiVersion: v1
kind: Pod
metadata:
  name: value-from-sysvar
spec:
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      env:
        - name: ENV_KEYNAME_1
          valueFrom:
            configMapKeyRef:
              name: basic-configmap
              key: LOG_LEVEL
        - name: ENV_KEYNAME_2
          valueFrom:
            configMapKeyRef:
              name: special-configmap
              key: container
