apiVersion: v1
kind: Pod
metadata:
  name: env-from-volume
spec:
  volumes:
    - name: v-cm-basic           # 컨피그맵 볼륨
      configMap:
        name: basic-configmap    # 키/값을 가져올 컨피그맵 이름
  containers:
    - name: my-container
      image: busybox
      args: ['tail', '-f', '/dev/null']
      volumeMounts:
        - name: v-cm-basic       # volumes 에서 정의한 컨피그맵 볼륨 이름
          mountPath: /etc/config # 마운트 된 컨피그맵 경로
