apiVersion: v1
kind: Pod
metadata:
  name: conf-from-file
spec:
  volumes:
    - name: nginx-conf-vol       # 컨피그맵 볼륨
      configMap:
        name: nginx-conf         # 키/값을 가져올 컨피그맵 이름
  containers:
    - name: my-container
      image: nginx:latest
      volumeMounts:
        - name: mysql-conf-vol    # volumes 에서 정의한 컨피그맵 볼륨 이름
          mountPath: /etc/nginx   # 마운트 된 컨피그맵 경로
