apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-webserver
spec:
  replicas: 3
  selector:
    matchLabels:  # matchLabels 에 있는 라벨이 붙은 파드들을 리플리카셋으로 묶음.
      app: nginx
    template:
      metadata:
        name: pod-webserver
        labels:
          app: nginx
      spec:
        containers:
          - name: webserver
            image: nginx:latest
            ports:
              - containerPort: 80
