apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-webserver
spec:
  replicas: 3
  selector:
    matchLabels:  # matchLabels 에 있는 라벨이 붙은 파드들을 리플리카셋으로 묶음.
      app: nginx
  template:
    metadata:
      # 같은 네임스페이스에 중복되는 파드 이름은 불가하므로 이 이름은 무시된다.
      # 대신 <replicaset 이름>-<해시값> 으로 각 파드 이름이 만들어짐.
      name: pod-webserver
      labels:
        app: nginx
    spec:
      containers:
        - name: webserver
          image: nginx:latest
          ports:
            - containerPort: 80
